### ISSUE TITLE
Process runs in background after closing window

### ISSUE THREAD

**Issue by foguetes** [pietrop/digital-paper-edit-electron#43] opened 2020-05-15 14:51 UTC
I am using a Windows 10 machine. 
When I close autoedit I see the process is still running in the background using Task Manager.
If I try to open autoedit again the app window takes a very long time to show up, although the process is still running, as I said.

System specs as follows:

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.18362 Build 18362
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-ISJR7QS
System Manufacturer	Alienware
System Model	Alienware Area-51 R5
System Type	x64-based PC
System SKU	836
Processor	Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz, 3096 Mhz, 14 Core(s), 28 Logical Processor(s)
BIOS Version/Date	Alienware 2.0.3, 27.05.2019
SMBIOS Version	3.0
Embedded Controller Version	17.09
BIOS Mode	UEFI
BaseBoard Manufacturer	Alienware
BaseBoard Product	0N4R4N
BaseBoard Version	A00
Platform Role	Desktop
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume8
Locale	United States
Hardware Abstraction Layer	Version = "10.0.18362.752"
```

**Comment by pietrop** [comment] 2020-05-15 15:19
Thanks, @foguetes

> close autoedit I see the process is still running in the background

 I wonder if there's something I should improve in [src/electron-main.js](https://github.com/pietrop/digital-paper-edit-electron/blob/master/src/electron-main.js)?

on a mac there is this [/src/electron-main.js#L173-L179](https://github.com/pietrop/digital-paper-edit-electron/blob/master/src/electron-main.js#L173-L179) (which is from electron's docs [Writing Your First Electron App](https://www.electronjs.org/docs/tutorial/first-app)) but I don't see anything specific for Windows?

or whether it is by design, eg the main process is always running, until you close the app. The render process, the one that shows you the window (and that there can be multiple of) can be opened and closed but closing a window doesn't close the app, coz the main process is still running, until the app is closed, if that makes sense? If I got this right, more in this in electron's docs [Electron Application Architecture](https://www.electronjs.org/docs/tutorial/application-architecture) 
---

>the app window takes a very long time to show up

I was also looking at electron's new version 8 and the [Deprecation of remote Module (Starting in Electron 9)](https://www.electronjs.org/blog/electron-8-0#deprecation-of-remote-module-starting-in-electron-9)

I suspect some of the use of `remote` module, might be causing the slow startup time, but not 100% sure. 

In any case it needs refactoring to change it as explained in this comment https://github.com/electron/electron/issues/21408#issuecomment-564184702

And just to confirm,  we are talking about autoEdit3 (and not autoEdit2)

**Comment by pietrop** [comment] 2020-05-16 01:01
Try this release [1.2.6](https://github.com/pietrop/digital-paper-edit-electron/releases/tag/1.2.6) if you get a chance, curious to see if startup time improves. 

( some [notes here on the changes made, removing remote in favor of ipc communication](https://github.com/pietrop/digital-paper-edit-electron/blob/master/docs/notes/2020-05-14-electron-remote-refactor.md) )

**Comment by foguetes** [comment] 2020-06-02 07:31
The problem persists in version [3-1.2.12
](https://github.com/pietrop/digital-paper-edit-electron/releases/download/1.2.12/autoEdit-3-1.2.12.exe).

I open the app but the app windows takes several minutes to show up.

When I try to open the developer console I get this error:

![image](https://user-images.githubusercontent.com/25814516/83492364-76f39e80-a4b3-11ea-856a-0f517ff6dc44.png)

**Comment by pietrop** [comment] 2020-06-02 15:12
Thanks @foguetes 
What’s the full path of the `C:\...` not the username but where there are the `...` before the `13`. Curious to see if it points to a specific file/module?

**Comment by pietrop** [comment] 2020-06-02 15:17
Altho I think it could be a bug in the menu 

[/src/make-menu-template.js#L119](https://github.com/pietrop/digital-paper-edit-electron/blob/a072f5b367a8c025297970b8ad96332d55f9bc22/src/make-menu-template.js#L119) where it assumes there is a `win` object that it’s not in scope.

Could you open the inspector / console using keyboard shortcuts?

cmd + alt + i 

on Mac, so on PC should be 

Windows key + alt + i?

**Comment by sqr** [comment] 2020-06-04 23:02
Hello Pietro, 
I am also facing this issue in Windows 10. 
I have tried looking for the full path for the error but can't seem to find it, as I get no JS errors on the console.

I have been looking at the different .js files loaded to see if one can have a conflicting line 13. 

switch.js, Lifecycle.js, HashRouter.js, BrowserRouter.js and withRouter.js all seem to have code related to React on line 13. 

If there is any other way I can help you solve the issue let me know!

**Comment by pietrop** [comment] 2020-06-09 16:16
### `win` error 
ok removing the win object mentioned here https://github.com/pietrop/digital-paper-edit-electron/issues/43#issuecomment-637609364 and releasing new version`1.2.14`

### slow startup time 
continuing the conversation around performance issues in windows as part of this other issue https://github.com/pietrop/digital-paper-edit-electron/issues/44

### background process
 As I think the background process is default behaviour for electron, eg if you close a window, the app is still running until you close the app. if that makes sense?

but if that is not the case, feel free to re-open this issue.

**Closed by pietrop** 2020-06-09 16:16 UTC
Labels: bug
